from .ArithMean import ArithMean
from .ChiSquare import ChiSquare
from .kstest import kstest
from .Levene import Levene
from .SeperatingGroup import SeperatingGroup
from .singleton import Singleton
from .Std_dev import Std_dev
from .Variance import Variance
from .Wilcoxon import Wilcoxon
from .ZScore import ZScore
